# Generated by Django 6.0.3 on 2026-03-13 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Jméno interpreta')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biografie')),
                ('image', models.ImageField(blank=True, null=True, upload_to='artists/', verbose_name='Fotografie')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Název alba')),
                ('release_date', models.DateField(verbose_name='Datum vydání')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='albums/', verbose_name='Obal alba')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='melody.artist', verbose_name='Interpret')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Název skladby')),
                ('duration', models.IntegerField(verbose_name='Délka (v sekundách)')),
                ('audio_file', models.FileField(upload_to='tracks/', verbose_name='Audio soubor')),
                ('genre', models.CharField(max_length=100, verbose_name='Žánr')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='melody.album', verbose_name='Album')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Název playlistu')),
                ('is_public', models.BooleanField(default=False, verbose_name='Veřejný playlist')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL, verbose_name='Vlastník')),
                ('tracks', models.ManyToManyField(blank=True, related_name='playlists', to='melody.track', verbose_name='Skladby')),
            ],
        ),
    ]
